[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 200
via_ir = true

always_use_create_2_factory = true

[invariant]
runs = 64           # Reduce from default 256
depth = 15          # Reduce call depth from default 500  
fail_on_revert = false
call_override = false
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[fuzz]
runs = 256